import { InscriptionRecord } from '../data/inscriptions';

export function exportToEpiDocXml(record: InscriptionRecord): string {
  return `<?xml version="1.0" encoding="UTF-8"?>
<TEI xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
    <fileDesc>
      <titleStmt>
        <title>${record.title}</title>
        <editor>EpigraphAI Automatic Vision System</editor>
      </titleStmt>
      <publicationStmt>
        <authority>EpigraphAI Digital Corpus</authority>
        <idno type="record-id">${record.id}</idno>
        <availability><p>Creative Commons Attribution 4.0 International</p></availability>
      </publicationStmt>
      <sourceDesc>
        <msDesc>
          <msIdentifier>
            <settlement>${record.location}</settlement>
            <repository>${record.siteName}</repository>
          </msIdentifier>
          <physDesc>
            <objectDesc>
              <supportDesc>
                <support>${record.substrate}</support>
                <condition>${record.conservationStatus}</condition>
              </supportDesc>
            </objectDesc>
          </physDesc>
          <history>
            <origin>
              <origDate>${record.approxDate} (${record.period})</origDate>
              <origPlace>
                <geo>${record.gps.lat}, ${record.gps.lng}</geo>
              </origPlace>
            </origin>
          </history>
        </msDesc>
      </sourceDesc>
    </fileDesc>
    <profileDesc>
      <langUsage>
        <language ident="tam-Brah">Tamil-Brahmi / Vatteluttu</language>
        <language ident="tam">Modern Tamil</language>
        <language ident="san-Gran">Sanskrit in Grantha</language>
        <language ident="eng">English</language>
      </langUsage>
    </profileDesc>
  </teiHeader>
  <text>
    <body>
      <div type="edition" subtype="epigraphai-ocr" cert="${(record.confidenceScore / 100).toFixed(2)}">
        <ab>
          <seg type="ancient-glyphs">${record.rawAncientText}</seg>
        </ab>
      </div>
      <div type="transliteration" xml:lang="tam">
        <p>${record.modernTamilText}</p>
      </div>
      <div type="translation" xml:lang="eng">
        <p>${record.englishTranslation}</p>
      </div>
      <div type="commentary">
        <p>${record.historicalSignificance}</p>
      </div>
    </body>
  </text>
</TEI>`;
}

export function exportToGeoJson(record: InscriptionRecord): string {
  const geoObj = {
    type: 'FeatureCollection',
    features: [
      {
        type: 'Feature',
        geometry: {
          type: 'Point',
          coordinates: [record.gps.lng, record.gps.lat],
        },
        properties: {
          id: record.id,
          title: record.title,
          script: record.scriptType,
          dynasty: record.dynasty,
          period: record.period,
          approxDate: record.approxDate,
          site: record.siteName,
          location: record.location,
          modernTamil: record.modernTamilText,
          englishTranslation: record.englishTranslation,
          confidence: record.confidenceScore,
        },
      },
    ],
  };
  return JSON.stringify(geoObj, null, 2);
}

export function exportToMarkdown(record: InscriptionRecord): string {
  return `# Archaeological Field Report: ${record.title}
*Generated by EpigraphAI Computer Vision System*

---

## 1. Physical & Geographic Metadata
- **Record Identifier:** \`${record.id}\`
- **Script Type:** ${record.scriptType}
- **Dynasty:** ${record.dynasty}
- **Period / Date:** ${record.period} (~${record.approxDate})
- **Monument / Site:** ${record.siteName}
- **Location:** ${record.location}
- **GPS Coordinates:** ${record.gps.lat}° N, ${record.gps.lng}° E
- **Stone Substrate:** ${record.substrate}
- **Conservation Status:** ${record.conservationStatus}
- **Model Confidence Score:** ${record.confidenceScore}%

---

## 2. Inscriptional Transcription & Decipherment
### Ancient Script Sequence
> ${record.rawAncientText}

### Modern Tamil Transliteration
> **${record.modernTamilText}**

${record.sanskritIast ? `### Sanskrit (IAST)\n> *${record.sanskritIast}*\n` : ''}

### English Translation
> "${record.englishTranslation}"

### Modern Tamil Meaning
> ${record.tamilMeaning}

---

## 3. Palaeographical Analysis & Key Characteristics
${record.palaeographicFeatures.map(f => `- ${f}`).join('\n')}

---

## 4. Historical Significance & Archaeological Context
${record.historicalSignificance}

---
*Preserving Epigraphical Heritage with Computer Vision & Deep Learning (ASI / Tamil Nadu Archaeology aligned)*
`;
}

export function downloadFile(filename: string, content: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
